### ISSUE TITLE
[Bug] Action buttons covered by footer

### ISSUE THREAD

**Issue by nutrina** [passportxyz/passport#2840]
This problem can be reproduced:
- on iOS in browser like Safari and Metamask
- in Safari on Desktop when testing in very small screen

The problem:
- use a small screen size (mobile size)
- the action button `Skip` and `Next` are initially visible
- however when scrolling to the bottom of the page this buttons are covered by the footer

This has worked well in Chrome and Firefox on desktop.

![Image](https://github.com/user-attachments/assets/bc17ff05-ed03-4f0d-82f6-70e9d68602f7)

**Comment by tim-schultz** [comment]
@erichfi it looks like this issue was resolved. I did not ice that the mobile design is different than what we currently have in Figma. Should we update the mobile layout to match https://www.figma.com/design/FOOlLEFaBt87atw6CPkA5P/Passport-App?node-id=11875-28430&t=sWyteemNV9Bh4VLJ-1 or has the layout changed?

![Image](https://github.com/user-attachments/assets/e811f16e-16de-4ae1-98a5-4a865b7b00b5)
