### ISSUE TITLE
Spike: ARB Stylus

### ISSUE THREAD

**Issue by Jkd-eth** [passportxyz/passport#3042]
### User Story:
As the Passport Product team
We want to understand what is feasible with ARB Stylus
So that we can apply for a grant to expedite the work

### Acceptance Criteria
GIVEN 2 days to research
WHEN we are able to investigate and play with Stylus
THEN we can determine if it makes sense to apply for a grant

Let's spend up to 2 days researching ARB Stylus

Outcome: 1 or more features that we can think we can build that will further Passport and we can use to apply for a Stylus grant

Here are some resources:
- Stylus[ Discord thread](https://discord.com/channels/1201910237238399006/1303743786089971713/1303743788640108555)
- [Tweet](https://x.com/EntropyAdvisors/status/1853882250300973463) about launch
- Documentation: [RFP Categories](https://docs.google.com/document/d/1O5w_ybN3AXp2HjxTOFhwoinIM4tjjwHcPasHqiZKIe8/edit?tab=t.0#heading=h.cu6wop966ohx), [Gas Savings](https://docs.arbitrum.io/stylus/concepts/stylus-gas#stylus-gas-costs), [Recommended Libraries](https://docs.arbitrum.io/stylus/recommended-libraries). 
- [Grading Rubric ](https://docs.google.com/document/d/1ZQ5-odjtcoRN2LpTEhu8IemZg01Lz-VMKLh7tp-WtGY/edit?tab=t.0#heading=h.foq1rmanxarn)
- [ARB Stylus Forum Post](https://forum.arbitrum.foundation/t/stylus-sprint-important-resources-faq/27420)

Ideas:

- [ ] onchain scoring - creating the ability for others to create the own scores easily, do the computation on chain through a smart contract reading the data from the onchain Passport Bitmap
- [ ] Replacing Bitmap with human readable credentials
- [ ] Enabling user generated VCs
- [ ] Crate to verify VCs onchain

#### Product & Design Links:
<links>

#### Notes/Assumptions:

**Comment by tim-schultz** [comment]
@Jkd-eth We had a great discussion about possible use cases and came up with the following ideas:

## Claiming stamps across accounts: 

We discussed a way to allow users to claim stamps across accounts, write them on chain, then use then prove ownership anonymously from any wallet via smart contract calls. The idea very closely follows the architecture of Tornado Cash, but instead of depositing/withdrawing tokens you would be proving credentials.

The big benefit would be gas costs. It looks like TC [deposits](https://etherscan.io/tx/0x6836fce9e11413d832ec75fbb156cea46e97eb7c2348752f9c8f6a86b0454a09) are quite expensive and costs should reduce dramatically on stylus

The downside here is that we would just qualify for the `open applications` track.

## VC/Signature Verification Utility
We all agreed that this could be a good use case. But, after the meeting I found a number of utilities that Open Zeppelin created for stylus and ECDSA verification is one of them so doesn't look like this would end up adding much value
