### ISSUE TITLE
System Tests / Monitoring

### ISSUE THREAD

**Issue by nutrina** [passportxyz/passport#3088]
Given I am one of the passport engineers
I need to have possibility to monitor the correct functionality of any API in production 
in order to ensure the correct functionality of our system

### Tech Details
- the current solutions we have explored UR and DDog are limit (unable to test complex scenarios requiring wallet signature)
- the current idea is:
  - create a suite of system tests (for example using [jest](https://jestjs.io) and [puppeteer](https://pptr.dev ) that test the more complex APIs:
    - [ ] signing in using SIWE / Ceramic )
    - [ ] claiming stamps
    - [ ] getting payloads for writing passports on-chain
  - save the results in the DB
  - create a schedule run for these tests in our own infra (using a scheduled lambda for example)
- very important: we need to able to query for the latest run status and timestamps externally, in order to monitor the health of the runs and our system externally (from within UR or DDog). So the status & timestamp of the latest run should be exposed on a public endpoint.

**Comment by lucianHymer** [comment]
Here are the tests I'm thinking we can do, at least for a first iteration

Passport:
Log in
Claim NFT Stamp, see score increase
Delete NFT Stamp, see score decrease
Switch to Test mode and test minting passport - if it works with the refresh, do this through the customization so that we are also testing the customization flow. Otherwise, use the session storage variable directly to enable test mode.



Do we want to test Scorer now? If so
Log in
Create community
Create key
Delete key
Delete community

Do we want to test staking now?

**Comment by nutrina** [comment]
- focus should be in creating unit tests to cover testing all (or most) our complex endpoints:
  - calls to the `ceramic-cache` endpoint that requires a JWT token
  - calls to IAM to verify a web3 stamp
- we do not want to do UI tests for this ticket (we'll have a different ticket)
